export const images = [
  {
    "id": "0",
    "picture": "https://picsum.photos/id/1005/100/100",
    "username": "alejandroescamilla",
    "post_url": "https://picsum.photos/id/0/370/250/",
    "title": "Leo duis ut",
    "price": "220",
    "likes": "12",
    "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua",
    "tags": "risus,nullam,eget,felis,eget",
  },
  {
    "id": "1",
    "picture": "https://picsum.photos/id/1005/100/100",
    "username": "alejandroeescamilla",
    "post_url": "https://picsum.photos/id/1001/370/250/",
    "title": "Amet porttitor eget",
    "price": "450",
    "likes": "89",
    "description": "In aliquam sem fringilla ut morbi tincidunt augue interdum.",
    "tags": "pellentesque,habitant,morbi,tristique,senectus",
  },
  {
    "id": "10",
    "picture": "https://picsum.photos/id/1005/100/100",
    "username": "pauljarvis",
    "post_url": "https://picsum.photos/id/1015/250/370/",
    "title": "Habitasse platea dictumst",
    "price": "120",
    "likes": "98",
    "description": "Non nisi est sit amet facilisis magna etiam tempor.",
    "tags": "cursus,eget,nunc,scelerisque,viverra",
  },
  {
    "id": "100",
    "picture": "https://picsum.photos/id/1005/100/100",
    "username": "tinarataj",
    "post_url": "https://picsum.photos/id/1012/370/250/",
    "title": "Posuere sollicitudin aliquam",
    "price": "980",
    "likes": "43",
    "description": "Aliquet enim tortor at auctor urna nunc id cursus metus.",
    "tags": "volutpat,consequat,mauris,nunc,congue",
  },
  {
    "id": "1000",
    "picture": "https://picsum.photos/id/1005/100/100",
    "username": "lukasbudimaier",
    "post_url": "https://picsum.photos/id/1016/250/370/",
    "title": "Porta non pulvinar",
    "price": "340",
    "likes": "29",
    "description": "Porttitor eget dolor morbi non arcu risus quis varius quam.",
    "tags": "scelerisque,varius,morbi,enim,nunc",
  },
  {
    "id": "1001",
    "picture": "https://picsum.photos/id/1005/100/100",
    "username": "daniellemacInnes",
    "post_url": "https://picsum.photos/id/1019/370/250/",
    "title": "Habitasse platea dictumst",
    "price": "120",
    "likes": "98",
    "description": "Non nisi est sit amet facilisis magna etiam tempor.",
    "tags": "cursus,eget,nunc,scelerisque,viverra",
  },
  {
    "id": "1002",
    "picture": "https://picsum.photos/id/1005/100/100",
    "username": "nasa",
    "post_url": "https://picsum.photos/id/1002/370/250/",
    "title": "Porta non pulvinar",
    "price": "340",
    "likes": "29",
    "description": "Porttitor eget dolor morbi non arcu risus quis varius quam.",
    "tags": "scelerisque,varius,morbi,enim,nunc",
  },
]
